- name: install necessary system packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - nfs-utils
      - net-tools
      - ntp
      - docker
      - wget
      - git
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - vim
      - unzip
      - atomic-openshift-utils
      - kexec-tools
      - sos
      - psacct
      - dnsmasq
      - iptables-services
