- name: setup heketi key
  copy:
    src: id_rsa
    dest: /etc/heketi/heketi_key
    owner: heketi
    group: heketi
    mode: 0400 

- name: update /etc/profile for using heketi RESTAPI
  template:
    src: heketi.sh
    dest: /etc/profile.d/heketi.sh

    #- name: wait for port heketi become ready
    #  wait_for: 
    #    port: 8080
    #    state: present

- name: create heketi configuration file
  template:
    src: heketi.json
    dest: /etc/heketi/heketi.json
    backup: yes
    owner: heketi
    group: heketi
  notify:
  - restart heketi
