- name: load images to registry
  shell: for i in `ls *.tar` ; do docker load -i $i; done;
  args:
    chdir: /opt/images  


- name: modify registry server's docker config file
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: 'OPTIONS='
    line: "OPTIONS='--selinux-enabled --log-driver=json-file --signature-verification=false --insecure-registry {{public_registry.0}}'"
  notify:
    - restart Docker service

- name: create tag for images
  shell: for i in $(docker images|grep registry.access.redhat.com|awk '{print $1":"$2}') ; do docker tag  $i "{{public_registry.0}}$(echo $i|awk -F 'com' {'print $2'})" ; done;

- name: push images to local registry
  shell: for i in `docker images|grep {{public_registry.0}}|awk '{print $1":"$2}'` ; do docker push $i; done;

- name: delete redhat's official image tag
  shell: for i in $(docker images|grep {{public_registry.0}}|awk '{print $1":"$2}') ; do docker rmi  $i ; done; 
